### ISSUE TITLE
Don't check current day

### ISSUE THREAD

**Issue by Pexavo** [Pexavo/Abacadabra#3]
The system is checking current day aswell. This leads to redundant error messages.

As a abacadabra system user I don't want to see errors that I can't repair i.e. adding last entry of the day that did not end yet.

**Comment by kwitee** [comment]
Parhaps we can still keep checking the current day, but change the color to lighter shade of red to be less bothersome? There surely is value in checking the current day.

**Comment by Pexavo** [comment]
The background color of the current day entry has been changed to green and text has been added to status column: "Today".
Rest of the warning messages are preserved as per @kwitee 's recommendation.
